#Whether to have Legendary Battle Styles instantly break the unfair armor anyone who wears it. (MekaSuit, Draconic Armor, ProjectE Armors, Infinity Armor, etc.)
legendary_battle_style_can_puncture_invincibility = true
#Whether to have Imperatrice Lumiere unconditionally riposte when executing a spot-dodge (Debug purposes only)
unconditional_riposte = true

