
["Game Setting"]
	#小建筑和主建筑的最小区块间距
	#Range: > 0
	min_chunk_between_structure = 3
	#是否在进入游戏时直接给予玩家维度传送钥匙以及进入维度后给新手奖励
	give_m_key = true
	#允许进入维度的玩家血量范围
	#Range: 1.0 ~ 1.7976931348623157E308
	health_check = 25.0
	#是否允许bvb 开启后boss可离开祭坛活动
	allow_bvb = false
	#是否全局广播剧情对话
	broadcast_dialog = true
	#广播范围
	#Range: 1.0 ~ 1.7976931348623157E308
	broadcast_distance = 50.0

["Monster Setting"]
	#世界等级提升时怪物的属性提升倍数
	#Range: 1.0 ~ 1.7976931348623157E308
	mob_multiplier_when_world_level_up = 1.414
	#怪物生成间距
	#Range: 1.0 ~ 1.7976931348623157E308
	mob_spawn_distance = 20.0
	#精英怪的血量加倍
	#Range: 1.0 ~ 1.7976931348623157E308
	elite_mob_health_multiplier = 3.0
	#精英怪的伤害加倍
	#Range: 1.0 ~ 1.7976931348623157E308
	elite_mob_damage_multiplier = 1.5
	#是否在多人模式下boss血量增加
	boss_health_and_loot_multiple = true
	#多人模式下boss血量增加的最大倍数
	#Range: > 1
	boss_health_and_loot_multiple_max = 5
	#默认决斗范围
	#Range: > 1
	spawner_block_protect_radius = 20

[Test]
	#测试用x， 方便实时调某个数值
	#Range: -4.9E-324 ~ 1.7976931348623157E308
	test_x = 1.0
	#测试用y， 方便实时调某个数值
	#Range: -4.9E-324 ~ 1.7976931348623157E308
	test_y = 1.0
	#测试用z， 方便实时调某个数值
	#Range: -4.9E-324 ~ 1.7976931348623157E308
	test_z = 1.0
	#结构方块是否立即加载（开发人员用）
	enable_better_structure_block_load = true
	#速杀boss模式（开发人员用）
	fast_boss_fight = false

