
[logbegone]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", " has no attributes"]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Unknown variable: BIOME_SWAMP_HILLS", "[worlds_together] Error for jar:file:", "UUID of added entity already exists", "ThreadLocalRandom accessed from a different thread (owner: Server thread, current: C2ME worker", "[yesman.epicfight.api.data.reloader.ItemCapabilityReloadListener:apply]", "[minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file "]

