#the distance from player that martensite start working
Radius = 20.0
#the lowest chance that entity tick
"Minimal Chance" = 0.1
#Use the char you won't use in chunk name (Don't use speical char like backslash)
"Chunk Name Spliter" = "/"

