#the distance from player that martensite start working
Radius = 24.0
#the lowest chance that entity tick
"Minimal Chance" = 0.1
#Use modulo calculation to skip entity tick
"Modulo Skip Mode" = false
#Use the char you won't use in chunk name (Don't use speical char like backslash)
"Chunk Name Spliter" = "/"

