
#These settings define which perks are used and the settings which govern them.
[Perks]

	[Perks.For_Event]

		[[Perks.For_Event.SPRINT_JUMP]]
			perk = "pmmo:jump_boost"
			skill = "agility"
			per_level = 0.001

		[[Perks.For_Event.DEAL_DAMAGE]]
			perk = "pmmo:damage_boost"
			skill = "archery"
			applies_to = ["minecraft:bow", "minecraft:crossbow", "minecraft:trident"]

		[[Perks.For_Event.DEAL_DAMAGE]]
			perk = "pmmo:damage_boost"
			skill = "magic"
			applies_to = ["ars_nouveau:spell_bow"]

		[[Perks.For_Event.DEAL_DAMAGE]]
			perk = "pmmo:damage_boost"
			skill = "gunslinging"
			applies_to = ["cgm:pistol", "cgm:shotgun", "cgm:rifle"]

		[[Perks.For_Event.CROUCH_JUMP]]
			perk = "pmmo:jump_boost"
			skill = "agility"
			per_level = 0.0015

		[[Perks.For_Event.RECEIVE_DAMAGE]]
			for_damage = "minecraft:fall"
			perk = "pmmo:damage_reduce"
			skill = "agility"
			per_level = 0.025

		[[Perks.For_Event.RECEIVE_DAMAGE]]
			perk = "pmmo:attribute"
			skill = "endurance"

		[[Perks.For_Event.ENTITY]]
			perk = "pmmo:villager_boost"
			skill = "charisma"

		[[Perks.For_Event.BREAK_SPEED]]
			perk = "pmmo:break_speed"
			skill = "mining"
			pickaxe_dig = 0.005

		[[Perks.For_Event.BREAK_SPEED]]
			perk = "pmmo:break_speed"
			skill = "excavation"
			shovel_dig = 0.005

		[[Perks.For_Event.BREAK_SPEED]]
			perk = "pmmo:break_speed"
			skill = "woodcutting"
			axe_dig = 0.005

		[[Perks.For_Event.BREAK_SPEED]]
			perk = "pmmo:break_speed"
			skill = "farming"
			sword_dig = 0.005
			hoe_dig = 0.005
			shears_dig = 0.005

		[[Perks.For_Event.SUBMERGED]]
			perk = "pmmo:breath"
			skill = "swimming"

		[[Perks.For_Event.SUBMERGED]]
			perk = "pmmo:effect"
			skill = "swimming"
			min_level = 25
			effect = ""

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "mining"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "building"
			attribute = "forge:reach_distance"
			per_level = 0.05
			max_boost = 10.0

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "building"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "excavation"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "woodcutting"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "farming"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "agility"
			attribute = "minecraft:generic.movement_speed"
			per_level = 0.002
			max_boost = 1.0

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "agility"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "endurance"
			attribute = "minecraft:generic.max_health"
			per_level = 0.25
			max_boost = 50.0

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "endurance"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "combat"
			attribute = "minecraft:generic.attack_damage"
			per_level = 0.8
			max_boost = 10000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "combat"
			attribute = "minecraft:generic.attack_knockback"
			per_level = 0.08
			max_boost = 80

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "gunslinging"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			skill = "archery"
			attribute = "minecraft:generic.attack_damage"
			applies_to = ["minecraft:bow", "minecraft:crossbow", "minecraft:trident"]
			per_level = 0.6
			max_boost = 10000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "smithing"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "flying"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "swimming"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "sailing"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "fishing"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "crafting"

		[[Perks.For_Event.SKILL_UP]]
			perk = "ars_scalaes:spell_damage"
			skill = "magic"
			per_level = 15
			max_boost = 7000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "ars_scalaes:mana_boost"
			skill = "magic"
			per_level = 40.0
			max_boost = 30000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "ars_scalaes:mana_regen"
			skill = "magic"
			per_level = 0.025
			max_boost = 100.0

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "slayer"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "hunter"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "taming"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "cooking"

		[[Perks.For_Event.SKILL_UP]]
			perk = ""
			skill = "alchemy"

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:fire_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:ice_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:lightning_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:holyspell_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:ender_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:blood_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:evocation_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:eldritch_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:nature_magic_resist"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:fire_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:ice_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:lightning_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:holy_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:ender_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:blood_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:evocation_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:eldritch_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:nature_spell_power"
			skill = "magic"
			per_level = 0.93
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:cooldown_reduction"
			skill = "magic"
			per_level = 0.05
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:summon_damage"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:cast_time_reduction"
			skill = "magic"
			per_level = 0.04
			max_boost = 3000.0

		[[Perks.For_Event.SKILL_UP]]
			perk = "pmmo:attribute"
			attribute = "irons_spellbooks:casting_movespeed"
			skill = "magic"
			per_level = 0.1
			max_boost = 3000.0

