onCull = true
MaxEntityEntities = 72
qualityModes = "NORMAL"
RenderWeather = "CLOSE"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = false
startTime = 127.254
chatFix = false
onGui = true
GuiRXTX = true
GuiFPS = true
GuiCPU = true
GuiGPU = true
GuiRAM = true
GuiEntityCount = true
GuiPlayerPos = true
GuiServer = true
GuiCameraTarget = true
Mood = false
Particle = false
BlockBreakParticleMode = "VERY_LOW"
MaxParticleDistance = 24
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = false
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 32
GuiViewMode = "NULL"
EntityCullFov = 160
MinDistance = 1
EntityDistance = 63
TickPerformance = true
