onCull = true
MaxEntityEntities = 256
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = true
RenderDisplayItem = true
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 97.916
chatFix = true
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = true
GuiServer = true
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "NORMAL"
MaxParticleDistance = 24
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = true
ParticleMaxAge = 32
GuiViewMode = "NULL"
EntityCullFov = 130
MinDistance = 5
EntityDistance = 128
TickPerformance = true
