
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.ba_bt]
				land_monolith = true
				land_obelisk = true
				bt_cultist = true

			[light_sources.settings.entities.terramity]
				dungeon_effigy = true
				dungeon_sentry = true
				simple_turret = true
				megabite = true
				hellrok = true

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				frog = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				stray = true
				item = true
				shulker = true
				salmon = true
				wandering_trader = true
				item_frame = true
				vindicator = true
				horse = true
				phantom = true
				minecart = true
				evoker = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = true
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				trader_llama = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				blaze = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				tnt_minecart = true
				hopper_minecart = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.pale_hound]
				pale_hound = true

			[light_sources.settings.entities.alexscaves]
				dinosaur_spirit = true
				nuclear_explosion = true

			[light_sources.settings.entities.mowziesmobs]
				umvuthana_raptor = true
				sculptor = true
				umvuthana_follower_raptor = true
				grottol = true
				ferrous_wroughtnaut = true

			[light_sources.settings.entities.epicacg]
				gs_yoimiya_sa_arrow = true
				genshin_arrow = true

			[light_sources.settings.entities.forbidden_arcanus]
				lost_soul = true

			[light_sources.settings.entities.eeeabsmobs]
				nameless_guardian = true
				guling_sentinel_heavy = true
				guling_sentinel = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				cursed_armor = true
				tank = true
				creeperling = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.born_in_chaos_v1]
				lifestealer_true_form = true
				krampus_henchman = true
				monstrous_easter_egg_projectile = true
				fallen_chaos_knight = true
				dark_vortex = true
				glutton_fish = true
				corpse_fish = true
				skeleton_thrasher = true
				siamese_skeletons = true
				spirit_guide = true
				lifestealer = true
				siamese_skeletonsleft = true
				bonescaller_not_despawn = true
				krampus = true
				bloody_gadfly = true
				zombie_clown = true
				siamese_skeletonsright = true
				thornshell_crab = true
				missioner = true
				maggot = true
				door_knight_not_despawn = true
				spiritof_chaos = true
				firelight_not_despawn = true
				nightmare_stalker = true
				baby_spider = true
				dread_hound = true
				supreme_bonescaller_not_despawn = true
				decaying_zombie_not_despawn = true
				baby_skeleton = true
				swarmer = true
				restless_spirit = true
				bonescaller = true
				phantom_creeper = true
				dire_hound_leader = true
				supreme_bonescaller = true
				mother_spider = true
				staffof_magic_arrows_2_projectile = true
				corpse_fly = true
				skeleton_thrasher_not_despawn = true

			[light_sources.settings.entities.traveloptics]
				summoned_vesper = true
				summoned_tremorsaurus = true
				aqua_grandmaster = true
				summoned_vallumraptor = true

			[light_sources.settings.entities.cataclysm]
				deepling = true
				laser_beam = true
				screen_shake = true
				netherite_monstrosity = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true

			[light_sources.settings.entities.quark]
				shiba = true
				forgotten = true
				toretoise = true
				glass_frame = true
				stoneling = true

			[light_sources.settings.entities.arphex]
				silverfish_spectre = true
				scorpion_striker = true
				maggot_larvae = true
				dungeon_trigger = true
				beetle_bulwark = true
				ant_arsonist = true
				roach_riverspawn = true
				spider_larvae = true
				centipede_evictor_larvae = true
				spider_lurker = true
				spider_brood = true
				hornet_harbinger = true
				blood_worm = true
				mosquito_morbidity = true
				long_legs_tiny = true
				long_legs = true
				web_funnel = true
				small_web = true
				random_ar_ph_ex = true
				fly_festerer = true
				butterfly_bewitcher = true
				spider_flat = true
				spider_recluse = true

			[light_sources.settings.entities.goety]
				wraith = true
				wartling = true
				warlock = true
				icy_spider = true
				heretic = true
				reaper = true
				muck_wraith = true
				web_spider = true
				maverick = true

			[light_sources.settings.entities.fromtheshadows]
				bulldrogioth = true
				nehemoth = true
				froglin = true

			[light_sources.settings.entities.tumbleweed]
				tumbleweed = true

			[light_sources.settings.entities.irons_spellbooks]
				pyromancer = true
				apothecarist = true
				poison_arrow = true
				necromancer = true
				archevoker = true
				priest = true
				chain_lightning = true
				ball_lightning = true
				poison_cloud = true
				dead_king_corpse = true
				blood_slash = true
				firefly_swarm = true
				cryomancer = true
				electrocute = true

			[light_sources.settings.entities.legendarycreatures]
				peacock_spider = true
				wisp = true
				hound = true
				bullfrog = true

			[light_sources.settings.entities.tombstone]
				spectral_bite = true

			[light_sources.settings.entities.vinery]
				mule = true
				wandering_winemaker = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.relics]
				spore = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				snowy_creeper = true
				bamboo_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.iceandfire]
				stymphalian_bird = true
				cockatrice = true
				lightning_dragon = true
				hippogryph = true
				hydra_multipart = true
				troll = true
				fire_dragon = true
				hydra = true
				ice_dragon = true
				cockatrice_egg = true
				deathworm = true
				dragon_multipart = true
				amphithere = true
				sea_serpent = true

			[light_sources.settings.entities.mia_mobs]
				rohana = true
				hagamizukin = true

			[light_sources.settings.entities.ars_nouveau]
				follow_proj = true
				starbuncle = true
				spell_proj = true
				bookwyrm = true
				drygmy = true
				whirlisprig = true

			[light_sources.settings.entities.celestisynth]
				star_monolith = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.difficult_spawners]
				evil_spirit = true

