
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				cow = true
				skeleton = true
				panda = true
				bee = true
				zombie = true
				item = true
				husk = true
				creeper = true
				spider = true
				wither_skeleton = true
				phantom = true
				hoglin = true
				item_frame = true
				painting = true
				glow_item_frame = true
				armor_stand = true
				villager = true
				squid = true
				salmon = true
				bat = true
				ravager = true
				witch = true
				evoker = true
				vex = true
				sheep = true
				tropical_fish = true
				lightning_bolt = true
				pig = true
				zombie_villager = true
				chicken = true
				potion = true
				cat = true
				pillager = true
				iron_golem = true
				vindicator = true
				experience_orb = true
				enderman = true
				ender_pearl = true
				trident = true
				arrow = true
				glow_squid = true
				slime = true
				zombified_piglin = true
				donkey = true
				skeleton_horse = true
				horse = true
				mule = true
				mooshroom = true
				drowned = true
				turtle = true
				piglin = true
				strider = true
				furnace_minecart = true
				blaze = true
				magma_cube = true
				piglin_brute = true
				ghast = true
				zoglin = true
				stray = true
				evoker_fangs = true
				snowball = true
				small_fireball = true
				cod = true
				tnt_minecart = true
				chest_minecart = true
				wandering_trader = true
				trader_llama = true
				cave_spider = true
				shulker = true
				fox = true
				fireball = true
				minecart = true
				frog = true
				axolotl = true
				silverfish = true
				pufferfish = true
				sniffer = true
				wolf = true
				rabbit = true
				snow_golem = true
				egg = true

			[light_sources.settings.entities.ars_nouveau]
				drygmy = true
				starbuncle = true
				whirlisprig = true
				gift_starby = true
				spell_proj = true
				follow_proj = true
				flying_item = true
				bookwyrm = true
				wilden_guardian = true

			[light_sources.settings.entities.mowziesmobs]
				ferrous_wroughtnaut = true
				umvuthana_follower_raptor = true
				grottol = true

			[light_sources.settings.entities.irons_spellbooks]
				necromancer = true
				archevoker = true
				priest = true
				lightning_lance = true
				icicle = true
				magic_missile = true
				summoned_zombie = true
				ball_lightning = true
				apothecarist = true

			[light_sources.settings.entities.terramity]
				green_fairy = true
				blue_fairy = true
				pink_fairy = true
				echo_bug = true
				duskrok = true
				gatmancer = true
				conjurling = true
				thunker = true
				megabite = true
				simple_turret = true
				holy_round_projectile_projectile = true
				anti_gravity_round_projectile_projectile = true
				onyx_blast_projectile_projectile = true
				dungeon_sentry = true
				dungeon_effigy = true
				uvogre = true
				unholy_lance_projectile = true
				virtue = true
				holy_round_projectile_no_gravity = true
				holy_beam = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				cave_creeper = true
				savannah_creeper = true
				snowy_creeper = true
				swamp_creeper = true
				hills_creeper = true
				spruce_creeper = true
				beach_creeper = true

			[light_sources.settings.entities.born_in_chaos_v1]
				dark_vortex = true
				dread_hound = true
				restless_spirit = true
				corpse_fly = true
				decaying_zombie = true
				bonescaller = true
				corpse_fish = true
				baby_skeleton = true
				skeleton_thrasher = true
				spiritof_chaos = true
				siamese_skeletons = true
				phantom_creeper = true
				zombie_bruiser = true
				swarmer = true
				mother_spider = true
				zombie_clown = true
				door_knight = true
				spirit_guide_assistant = true
				spirit_guide = true
				decrepit_skeleton = true
				fallen_chaos_knight = true
				baby_spider = true
				baby_skeleton_minion = true
				staffof_magic_arrows_2_projectile = true
				skeleton_demoman = true
				firelight_not_despawn = true
				zombie_fisherman = true
				firelight = true
				supreme_bonescaller = true
				bone_imp = true
				barrel_zombie = true
				missioner = true
				bloody_gadfly = true
				thornshell_crab = true
				nightmare_stalker = true
				maggot = true
				glutton_fish = true
				lifestealer = true
				zombie_lumberjack = true
				dire_hound_leader = true
				krampus_henchman = true
				siamese_skeletonsright = true
				siamese_skeletonsleft = true
				staffof_blindness_projectile = true
				missionary_charge = true
				diamond_termite = true

			[light_sources.settings.entities.mokels_bossfight_saphyra]
				saphyra_spawn = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				nightmare = true
				acolyte = true
				corrupted_pillager = true
				corrupted_vindicator = true
				revenant = true
				ghoul = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true

			[light_sources.settings.entities.illageandspillage]
				imp = true
				illager_soul = true
				camera_shake = true

			[light_sources.settings.entities.arphex]
				spider_lurker = true
				termite_tunneler_queen = true
				termite_tunneler_worker = true
				random_termite = true
				fly_festerer = true
				locust_landscourge = true
				spider_larvae = true
				spider_flat = true
				termite_tunneler_alate = true
				silverfish_spectre = true
				random_ar_ph_ex = true
				termite_tunneler_soldier = true
				termite_tunneler_king = true
				spider_brood = true
				spider_jump = true
				ant_arsonist = true
				roach_riverspawn = true
				blood_worm = true
				scorpion_striker = true
				scorpion_larvae = true
				long_legs_fly = true
				centipede_stalker = true
				centipede_evictor_larvae = true
				mosquito_morbidity = true
				small_web = true
				web_funnel = true
				scorpioid_chaser_hallucination = true
				bar = true
				maggot_larvae = true
				butterfly_bewitcher = true
				beetle_bulwark = true
				long_legs_tiny = true
				long_legs = true
				spider_larvae_tiny = true
				dragonfly_dreadnought = true
				beetle_tick_mite = true
				millipede_marauder = true
				moth_moontracker = true
				dungeon_trigger = true

			[light_sources.settings.entities.iceandfire]
				cockatrice = true
				troll = true
				ice_dragon = true
				fire_dragon = true
				dragon_multipart = true
				hippocampus = true
				hydra_multipart = true
				hydra = true
				stymphalian_bird = true
				stymphalian_arrow = true
				sea_serpent = true
				siren = true
				ice_dragon_charge = true
				fire_dragon_charge = true
				lightning_dragon = true
				stymphalian_feather = true
				pixie = true
				cyclops = true
				cylcops_multipart = true
				multipart = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.enigmaticaddons]
				dragon_breath_arrow = true

			[light_sources.settings.entities.quark]
				glass_frame = true
				wraith = true
				foxhound = true
				soul_bead = true
				toretoise = true
				stoneling = true
				shiba = true
				forgotten = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true
				dispenser_minecart = true
				red_merchant = true

			[light_sources.settings.entities.forbidden_arcanus]
				lost_soul = true

			[light_sources.settings.entities.netherexp]
				apparition = true
				vessel = true
				wisp = true

			[light_sources.settings.entities.difficult_spawners]
				evil_spirit = true

			[light_sources.settings.entities.cataclysm]
				netherite_ministrosity = true
				netherite_monstrosity = true
				screen_shake = true
				laser_beam = true
				deepling_angler = true

			[light_sources.settings.entities.legendary_monsters]
				skeletosaurus = true

			[light_sources.settings.entities.tombstone]
				grave_guardian = true
				spectral_bite = true

			[light_sources.settings.entities.legendarycreatures]
				nether_wisp = true
				nether_wisp_purse = true
				corpse_eater = true

			[light_sources.settings.entities.relics]
				spore = true

			[light_sources.settings.entities.plenty_of_golems]
				first_of_basalt_statue = true
				ancient_of_prismarine_statue = true

			[light_sources.settings.entities.majruszsdifficulty]
				cursed_armor = true
				illusioner = true
				tank = true
				creeperling = true
				cerberus = true

			[light_sources.settings.entities.celestisynth]
				star_monolith = true

			[light_sources.settings.entities.eeeabsmobs]
				guling_sentinel = true

			[light_sources.settings.entities.vinery]
				mule = true
				wandering_winemaker = true

			[light_sources.settings.entities.traveloptics]
				aqua_grandmaster = true

			[light_sources.settings.entities.ba_bt]
				land_obelisk = true
				land_monolith = true

			[light_sources.settings.entities.regions_unexplored]
				boat = true

			[light_sources.settings.entities.alexscaves]
				subterranodon = true
				vallumraptor = true
				grottoceratops = true
				relicheirus = true
				trilocaris = true

			[light_sources.settings.entities.dungeons_plus]
				soul_fireball = true

			[light_sources.settings.entities.screamfromthecold]
				wendigo = true

			[light_sources.settings.entities.fromtheshadows]
				froglin = true

			[light_sources.settings.entities.dungeons_and_combat]
				hermit_witch = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

